//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.586
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snip.BP.BO.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snip.BP.BO.Recursos.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Cantidad no puede ser cero o menor que cero..
        /// </summary>
        internal static string CantidadNotZeroOrNegative {
            get {
                return ResourceManager.GetString("CantidadNotZeroOrNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca la descripción para este elemento..
        /// </summary>
        internal static string DescripcionNotEmpty {
            get {
                return ResourceManager.GetString("DescripcionNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir la Fecha Estimada de Inicio de la Licitación..
        /// </summary>
        internal static string FechaInicioNotEmpty {
            get {
                return ResourceManager.GetString("FechaInicioNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir la Fecha solicitada..
        /// </summary>
        internal static string FechaNotEmpty {
            get {
                return ResourceManager.GetString("FechaNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir una fecha válida..
        /// </summary>
        internal static string FechaNotValid {
            get {
                return ResourceManager.GetString("FechaNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha fuera del rango permitido..
        /// </summary>
        internal static string FechaRangeNotValid {
            get {
                return ResourceManager.GetString("FechaRangeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca el identificador para este elemento..
        /// </summary>
        internal static string IdentificadorNotNullOrEmpty {
            get {
                return ResourceManager.GetString("IdentificadorNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Monto no puede ser cero. Debe Registrar una cantidad..
        /// </summary>
        internal static string MontoNotZero {
            get {
                return ResourceManager.GetString("MontoNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Monto no puede ser menor que cero o negativo..
        /// </summary>
        internal static string MontoNotZeroOrNegative {
            get {
                return ResourceManager.GetString("MontoNotZeroOrNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca el nombre para este elemento..
        /// </summary>
        internal static string NombreNotNullOrEmpty {
            get {
                return ResourceManager.GetString("NombreNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe digitar las siglas.
        /// </summary>
        internal static string SiglasNotNullOrEmpty {
            get {
                return ResourceManager.GetString("SiglasNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir un valor para este elemento..
        /// </summary>
        internal static string ValorNotNullOrEmpty {
            get {
                return ResourceManager.GetString("ValorNotNullOrEmpty", resourceCulture);
            }
        }
    }
}
